### ISSUE TITLE
`_generate` doesn't work

### ISSUE THREAD

**Issue by Alseidon** [abraemer/StartupCustomizer.jl#5]
I stumbled upon this when trying to follow the quick start on the README : `StartupCustomizer.add(StartupCustomizer.Revise())` ends up in an error `SystemError: opening file "templates/revise.jl": No such file or directory`.

I narrowed this down to the `_generate` function :
```julia
julia> import StartupCustomizer

julia> StartupCustomizer._generate(StartupCustomizer.Revise())
ERROR: SystemError: opening file "templates/revise.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:176
  [2] #systemerror#82
    @ ./error.jl:175 [inlined]
  [3] systemerror
    @ ./error.jl:175 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:275 [inlined]
  [6] open(f::Base.var"#418#419"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:393
  [7] open
    @ ./io.jl:392 [inlined]
  [8] read
    @ ./io.jl:473 [inlined]
  [9] _generate(#unused#::StartupCustomizer.Revise)
    @ StartupCustomizer ~/.julia/packages/StartupCustomizer/YKDad/src/modules/revise.jl:11
 [10] top-level scope
    @ REPL[2]:1
```

This would probably be solved by replacing `"templates/revise.jl"` with `joinpath(get_dir_src(), "templates/revise.jl")` and similarly for other modules I guess?

**Comment by abraemer** [comment]
Thanks a lot for the report! Of course I only tested the package from inside it's own folder...

This also revealed that this packages handles crashes kinda badly and the parsing is not very robust :sweat_smile: So I'll have to improve that a some point in the future as well.
